### ISSUE TITLE
TypeError: order must be str, not int

### ISSUE THREAD

**Issue by simin75simin** [imistyrain/MTCNN#19]
The problem:
╰─$ py python/demo.py      
Traceback (most recent call last):
  File "python/demo.py", line 86, in <module>
    test_camera(detector)
  File "python/demo.py", line 77, in test_camera
    boxes, points= detector.detect(img)
  File "/home/liutianyu/face-ais/head-pose-estimation/MTCNN-hpe/python/Mtcnndnn.py", line 199, in detect
    boxes = self.generateBoundingBox(map,reg,scale,self.threshold[0])
  File "/home/liutianyu/face-ais/head-pose-estimation/MTCNN-hpe/python/Mtcnndnn.py", line 106, in generateBoundingBox
    a = np.where(map.flatten(1)>=threshold)
TypeError: order must be str, not int

System info:
OS: ubuntu18.04

╰─$ py -m pip freeze                                                                                                                                                                                           1 ↵
numpy==1.19.5
opencv-python==4.5.4.60
pkg_resources==0.0.0

╰─$ py -V            
Python 3.6.9

**Comment by u7079256** [comment]
flatten(1) -> flatten() , this should solve the problem
